name: supabase_progress_uploads
description: A package for resumable file uploads with progress tracking, integrated with Supabase.
version: 1.0.4
homepage: https://github.com/itsatifsiddiqui/supabase_progress_uploads

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tus_client_dart: ^2.5.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.9.1
  uuid: ^4.5.1
  path: ^1.9.1
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
